exclude: ^([.]pnp[.]cjs|[.]pnp[.]loader[.]mjs|[.]yarn/.+?|.+?/[.]joblib_cache/.+?)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.252"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: nbqa-black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier

  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
