include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
target-version = "py311"
select = ["B", "C4", "E", "EXE", "F", "I", "ICN", "N", "SIM", "PD", "PGH", "RUF", "UP", "W"]
ignore = [
  "E501",
  "B018"  # useless expressions are not so useless in Jupyter notebooks
]

[isort]
force-single-line = true
required-imports = ["from __future__ import annotations"]
