[build]
  command = "yarn export"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/nvc"
  [headers.values]
    Cache-Control = "public, max-age=600"
